import "../../../styles.css";
import "../globals.css";
import "daisyui/dist/full.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "../../components/provider";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" data-theme={"light"}>
      <Script type="text/javascript" src={"/static/crisp.js"}></Script>

      <Provider>
        <body className={inter.className}>{children}</body>
      </Provider>
    </html>
  );
}
