/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokemonsPokemonIdRouteImport } from './routes/pokemons.$pokemonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonsPokemonIdRoute = PokemonsPokemonIdRouteImport.update({
  id: '/pokemons/$pokemonId',
  path: '/pokemons/$pokemonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemons/$pokemonId': typeof PokemonsPokemonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemons/$pokemonId': typeof PokemonsPokemonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pokemons/$pokemonId': typeof PokemonsPokemonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemons/$pokemonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemons/$pokemonId'
  id: '__root__' | '/' | '/pokemons/$pokemonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonsPokemonIdRoute: typeof PokemonsPokemonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemons/$pokemonId': {
      id: '/pokemons/$pokemonId'
      path: '/pokemons/$pokemonId'
      fullPath: '/pokemons/$pokemonId'
      preLoaderRoute: typeof PokemonsPokemonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonsPokemonIdRoute: PokemonsPokemonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
